export const FETCH_STAR_WARS_REQUEST = 'FETCH_STAR_WARS_REQUEST'
export const FETCH_STAR_WARS_SUCCESS = 'FETCH_STAR_WARS_SUCCESS'

export const CONFIRMATION = 'CONFIRMATION'

export const CANCELLED = 'CANCELLED'

export const FETCH_STAR_WARS_PLANET_REQUEST = 'FETCH_STAR_WARS_PLANET_REQUEST'
export const FETCH_STAR_WARS_PLANET_SUCCESS = 'FETCH_STAR_WARS_PLANET_SUCCESS'

export const QUEUE_CHANNEL_REQUESTS = 'QUEUE_CHANNEL_REQUESTS'

